import { NextResponse } from "next/server";
import { z } from "zod";
import { supabaseAdmin } from "@/lib/supabase/server";
import { sendSms } from "@/lib/sms";
import { normalizePhoneE164 } from "@/lib/validators";
import { formatCAD } from "@/lib/currency";

const requestSchema = z.object({
  customer_name: z.string().trim().min(1).max(120),
  contact_method: z.enum(["email", "phone"]),
  contact_value: z.string().trim().min(1).max(200),
  payment_method: z.enum(["etransfer", "cash"]),
  notes: z.string().trim().max(2000).optional().or(z.literal("")),
  items: z
    .array(
      z.object({
        product_id: z.string().uuid(),
        size_label: z.string().trim().min(1).max(40),
        quantity: z.number().int().min(1).max(999),
      })
    )
    .min(1),
});

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = requestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid form data", details: parsed.error.flatten() },
      { status: 400 }
    );
  }
  const data = parsed.data;

  // Normalize contact value.
  let contactValue = data.contact_value.trim();
  if (data.contact_method === "phone") {
    const norm = normalizePhoneE164(contactValue);
    if (!norm) {
      return NextResponse.json(
        { error: "Invalid phone number" },
        { status: 400 }
      );
    }
    contactValue = norm;
  } else {
    if (!z.string().email().safeParse(contactValue).success) {
      return NextResponse.json(
        { error: "Invalid email address" },
        { status: 400 }
      );
    }
  }

  const sb = supabaseAdmin();

  // Gate on ordering_open AND snapshot batch label.
  const { data: settingsRow, error: settingsErr } = await sb
    .from("settings")
    .select("ordering_open, ordering_window_label, owner_phone_e164, etransfer_email")
    .limit(1)
    .maybeSingle();

  if (settingsErr || !settingsRow) {
    return NextResponse.json(
      { error: "Settings not configured" },
      { status: 500 }
    );
  }
  if (!settingsRow.ordering_open) {
    return NextResponse.json(
      { error: "Ordering window is closed." },
      { status: 403 }
    );
  }

  // Fetch authoritative prices + names for every product in the cart.
  const productIds = Array.from(new Set(data.items.map((i) => i.product_id)));
  const { data: products, error: productsErr } = await sb
    .from("products")
    .select("id, name, price_cents, active")
    .in("id", productIds);
  if (productsErr || !products) {
    return NextResponse.json(
      { error: "Failed to look up products" },
      { status: 500 }
    );
  }
  const productMap = new Map(products.map((p) => [p.id, p]));
  for (const item of data.items) {
    const p = productMap.get(item.product_id);
    if (!p || !p.active) {
      return NextResponse.json(
        { error: `One of your items is no longer available.` },
        { status: 400 }
      );
    }
  }

  // Compute authoritative subtotal.
  let subtotal = 0;
  const orderItemsRows = data.items.map((item) => {
    const p = productMap.get(item.product_id)!;
    const line = p.price_cents * item.quantity;
    subtotal += line;
    return {
      product_id: item.product_id,
      product_name_snapshot: p.name,
      size_label: item.size_label,
      quantity: item.quantity,
      unit_price_cents: p.price_cents,
    };
  });

  // Insert order. order_number is generated by DB default.
  const { data: orderRow, error: insertErr } = await sb
    .from("orders")
    .insert({
      customer_name: data.customer_name.trim(),
      contact_method: data.contact_method,
      contact_value: contactValue,
      payment_method: data.payment_method,
      subtotal_cents: subtotal,
      notes: data.notes?.trim() || null,
      batch_label: settingsRow.ordering_window_label,
    })
    .select("id, order_number")
    .single();

  if (insertErr || !orderRow) {
    console.error("[orders] insert failed", insertErr);
    return NextResponse.json(
      { error: "Failed to record order. Please try again." },
      { status: 500 }
    );
  }

  // Insert order items.
  const itemsToInsert = orderItemsRows.map((r) => ({ ...r, order_id: orderRow.id }));
  const { error: itemsErr } = await sb.from("order_items").insert(itemsToInsert);
  if (itemsErr) {
    // Best-effort rollback so we don't leave a half-formed order.
    await sb.from("orders").delete().eq("id", orderRow.id);
    console.error("[orders] items insert failed, rolled back", itemsErr);
    return NextResponse.json(
      { error: "Failed to record order. Please try again." },
      { status: 500 }
    );
  }

  // Fire SMS notification. Failures are logged but do NOT block confirmation.
  try {
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "";
    const adminLink = siteUrl
      ? `${siteUrl}/admin/orders/${orderRow.id}`
      : `/admin/orders/${orderRow.id}`;
    const itemCount = data.items.reduce((s, i) => s + i.quantity, 0);
    const body = `New BWM order ${orderRow.order_number} from ${data.customer_name.trim()} — ${itemCount} items, ${formatCAD(subtotal)}. ${data.payment_method === "etransfer" ? "E-Transfer" : "Cash"}. View: ${adminLink}`;
    if (settingsRow.owner_phone_e164) {
      void sendSms({ to: settingsRow.owner_phone_e164, body });
    }
  } catch (err) {
    console.error("[orders] sms enqueue failed", err);
  }

  return NextResponse.json({
    order_number: orderRow.order_number,
    order_id: orderRow.id,
  });
}
